### ISSUE TITLE
Drain jobs ?

### ISSUE THREAD

**Issue by crownedgrouse** [erlnets/nkcluster#3]
Hi, only a question, not an issue .
Is there a way to ask a node to drain jobs, i.e. finish current running jobs and not accepting new one ?
Is it the current behavior, could this be a new feature ?
Regards

**Comment by crownedgrouse** [comment]
Is anybody here ? Here.... here... re....

**Comment by kalta** [comment]
You mean `nkcluster:set_status(Node, standby)` ?

**Comment by crownedgrouse** [comment]
Well, 'stopping' is more close to my need, but in the documentation you say it ask tasks to stop.
'draining' is a state where all tasks are waiting to be finish normally while no other tasks are accepted. 
But maybe I did not well understood those states...

**Comment by crownedgrouse** [comment]
Closing. Thanks
